%INCLUDE"time.asm"
%INCLUDE"date.asm"
%INCLUDE "up.asm"
%INCLUDE "console_io.asm"
%INCLUDE"enter_user.asm"
%INCLUDE"clearScreen.asm"
%INCLUDE"shoutdown.asm"
%INCLUDE "history.asm"
%INCLUDE"instructionre.asm"
%INCLUDE"echo.asm"
%INCLUDE"help.asm"
%INCLUDE"whoAmI.asm"
%INCLUDE"complete.asm"
%INCLUDE"halfStrCmp.asm"
%INCLUDE"clearArray.asm"
%INCLUDE "strcp.asm"
%INCLUDE "changeusrpas.asm"
%INCLUDE "setTime.asm"

